# Workflow name
name: Fetch WSJ daily value extraction

# ---------------------------------
# TRIGGER CONFIGURATION
# ---------------------------------
on:
  workflow_dispatch:
  schedule:
    - cron: '0 4,5 * * *' # Nebraska Time

# ---------------------------------
# JOB CONFIGURATION
# ---------------------------------
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Step 4: Install Playwright Browsers
      - name: Install Playwright Browsers
        run: playwright install --with-deps

      # Step 5: Create the Google Credentials File
      - name: Create Google Credentials File
        env:
          CREDENTIALS_JSON: ${{ secrets.GOOGLE_CREDENTIALS }}
        run: python -c "import os; f = open('google_creds.json', 'w'); f.write(os.environ['CREDENTIALS_JSON']); f.close()"

      # Step 6: Run the main Python scraper script
      - name: Run Python Scraper
        env:
          SHEET_ID: ${{ secrets.SHEET_ID }}
          GOOGLE_APPLICATION_CREDENTIALS: ./google_creds.json
        run: python wsj_value_fetcher.py
